# Uncomment this line to define a global platform for your project
platform :ios, "6.0"
link_with 'SDWebImageYLGIFImageDemo', 'SDWebImageYLGIFImageDemoTests'
pod 'SDWebImage', :git => 'https://github.com/liyong03/SDWebImage.git'
pod 'YLGIFImage'

